### PR TITLE
Sepa integration 2

### PR DESCRIPTION
**Pull request by Doppp**
From [Adyen](https://github.com/wvanbergen/adyen/pull/81).

### CODE REVIEW

**Comment by Doppp** [comment]
FYI, @azach. We forked this repo from the original because the maintainer is MIA. This was the PR which I initially had in his repo.

**Comment by Doppp** [comment]
@azach, should we merge this and put this on gemfury or something? Clerk is using this branch at the moment.

**Comment by azach** [comment]
I think it's fine to leave it as is until the original PR is merged.

**Comment by alan-andrade** [comment]
Pruning dead branches Doppp ? 🧹 nice

**Pull request closed without merging**
